theme = "Onedark"

[editor]
line-number = "relative"
cursorline = true
completion-trigger-len = 2
rulers = [80]
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ["match_brackets"]
