# Custom - Hydrogen

#spacing         = 2
#padding         = 2
hide_ascii      = false
separator       = ""
separator_color = "White"
key_color       = "Cyan"


[palette]
type            = "Dark" # Light or Full
glyph           = " "
visible         = true

[bar]
glyph           = ""
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = true

[box]
title           = "System Information"
border          = "thick"
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[randomize]
key_color       = false
separator_color = false

# [keys]
# host            = "Host"
# kernel          = "Kernel"
# battery         = "Battery"
# os              = "OS"
# de              = "DE"
# wm              = "WM"
# distro          = "Distro"
# terminal        = "Terminal"
# shell           = "Shell"
# packages        = "Packages"
# uptime          = "Uptime"
# memory          = "Memory"
# machine         = "Machine"
# local_ip        = "Local IP"
# backlight       = "Brightness"
# resolution      = "Resolution"
# cpu_load        = "CPU Load"
# cpu             = "CPU"