"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$cmd_duration$git_status$time"""
format = """$os$directory$character"""
add_newline = false

[os]
disabled = false

[os.symbols]
Macos = ' '

[time]
disabled = false
time_format = '%H:%M'
format = '[ $time]($style) '

[directory]
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1
