#!/bin/bash

###############################################################################
# Convert 1.0                                                                 #
# Altair Bueno MIT license                                                    #
# https://github.com/Altair-Bueno/Demeter                                     #
#                                                                             #
# Light wrapper around `pyscripts/src/convert.py`                             #
#                                                                             # 
###############################################################################

PYSCRIPTS="$DEMETER/scripts/pyscripts"
CONVERT="$PYSCRIPTS/src/convert.py"
POETRY_LOCK="$PYSCRIPTS/poetry.lock"

if [[ ! -f "$POETRY_LOCK" ]]
then
    echo "Couldn't find $POETRY_LOCK, installing packages"
    poetry install
fi

# Poetry doesn't support running on another directory...
WORKING_DIR=$(pwd)
cd "$PYSCRIPTS"
poetry run python "$CONVERT" ${@:1}
cd "$WORKING_DIR"