#!/bin/zsh

###############################################################################
# Demeter 1.0                                                                 #
# Altair Bueno MIT license                                                    #
# https://github.com/Altair-Bueno/Demeter                                     #
#                                                                             #
# This script provides a baseline for developing your own automator worklflow #
# with automatic uploads.                                                     #
#                                                                             # 
# 1. Create new Shortcuts Workflow                                            #
# 2. Use calendar trigger                                                     #
# 3. Use 'Run Shell script'                                                   #
# 4. Write the path to this script. For example                               #
#    `$HOME/Demeter/scripts/demeter`                                          #
###############################################################################

DEMETER="${DEMETER:-$HOME/Demeter}"
LOG_FILE="${LOG_FILE:-$DEMETER/gitlog.txt}"

COMMIT_MESSAGE="[$(date '+%d/%m/%y')]: Scheduled job on $(uname -n)"
COMMIT_MESSAGE="${1:-$COMMIT_MESSAGE}"

BREW_TAP="${BREW_TAP:-$DEMETER/packages/brew/tap.txt}"
BREW_PACKAGE="${BREW_PACKAGE:-$DEMETER/packages/brew/packages.txt}"
BREW_CASK="${BREW_CASK:-$DEMETER/packages/brew/cask.txt}"

if [[ $(uname) == 'Darwin' ]]
then
	mkdir -p "$(dirname "$BREW_TAP")" "$(dirname "$BREW_PACKAGE")" "$(dirname "$BREW_CASK")"
	brew tap > "$BREW_TAP"
	brew leaves > "$BREW_PACKAGE"
	brew list --cask > "$BREW_CASK"
else
	echo Freezing packages is not supported on non-macOS systems
fi

echo "$COMMIT_MESSAGE
********************************************************************************
" > "$LOG_FILE"

# Has changes?
if [[ $(git -C "$DEMETER" diff >> "$LOG_FILE") ]]
then 
	echo "No changes found"
else 
	# echo "true"
	echo "Found changes, updating"
	if [[ $( { git -C "$DEMETER" fetch && git -C "$DEMETER" merge } >> "$LOG_FILE" ) ]]
	then
		echo "Automatic merge failed. Check logs at $LOG_FILE"
	else 
  		git -C "$DEMETER" add --all >> "$LOG_FILE"
		git -C "$DEMETER" commit -am "$COMMIT_MESSAGE" >> "$LOG_FILE"
		git -C "$DEMETER" push  >> "$LOG_FILE"
		echo "Backup successful"
	fi
fi