#!/usr/bin/env -S zsh -eo pipefail
local context
context="$(
    kubectl config get-contexts -o name \
    | fzf "--query=$@" --select-1 \
        '--header=Choose a context'
)"
kubectl config use-context "$context"
