#!/usr/bin/env -S deno run -q --allow-read

import * as toml from "https://deno.land/std@0.152.0/encoding/toml.ts";
import * as yaml from "https://deno.land/std@0.152.0/encoding/yaml.ts";
import * as flags from "https://deno.land/std@0.152.0/flags/mod.ts";
import { readAll } from "https://deno.land/std@0.152.0/streams/conversion.ts";
import { z } from "https://deno.land/x/zod@v3.18.0/mod.ts";

const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();
const parsedFlags = flags.parse(Deno.args);

// Help
if (parsedFlags.h || parsedFlags.help) {
  console.table({
    "--from": {
      description: "Input format",
      type: "json|yaml|toml",
      default: "json",
    },
    "--to": {
      description: "Output format",
      type: "json|yaml|toml",
      default: "json",
    },
    "-o": { description: "Output file", type: "string", default: "[STDOUT]" },
    "": { description: "Input file", type: "string", default: "[STDIN]" },
  });
  Deno.exit();
}
// Validate commandline arguments
const args = z
  .object({
    from: z.enum(["yaml", "json", "toml"]).default("json"),
    to: z.enum(["yaml", "json", "toml"]).default("json"),
    _: z.array(z.string()).max(1),
    o: z.optional(z.string()),
  })
  .parse(parsedFlags);

const inputFile = args._[0] ? await Deno.open(args._[0]) : Deno.stdin;
const serializedInput = await readAll(inputFile);
inputFile.close();
const serializedInputString = textDecoder.decode(serializedInput);

let obj;
if (args.from === "yaml") {
  obj = yaml.parse(serializedInputString);
} else if (args.from === "toml") {
  obj = toml.parse(serializedInputString);
} else if (args.from === "json") {
  obj = JSON.parse(serializedInputString);
}

let serializedOutputString;
if (args.to === "yaml") {
  serializedOutputString = yaml.stringify(obj);
} else if (args.to === "toml") {
  serializedOutputString = toml.stringify(obj);
} else if (args.to === "json") {
  serializedOutputString = JSON.stringify(obj);
}
const serializedOutput = textEncoder.encode(serializedOutputString);
const outputFile = args.o ? await Deno.open(args.o) : Deno.stdout;
await outputFile.write(serializedOutput);
outputFile.close();
