#!/usr/bin/env zsh

###############################################################################
# Takeout 2.0                                                                 #
# Altair Bueno MIT license                                                    #
# https://github.com/Altair-Bueno/Demeter                                     #
#                                                                             #
# This shell script moves all elements out of a given directory to the parent #
# folder. This will delete the original folder but files will be preserved    #
# on the parent folder                                                        #
#                                                                             #
# Althought this script can be used as utility from the commandline i mainly  #
# use it for macOS Automator:                                                 #
# Right click > Services > Take files out of folder                           #
###############################################################################

target_directory="${1:-$PWD}"
parent_directory="$(dirname target_directory)"

if ! [[  -d "$target_directory" ]]
then
	echo "$target_directory is not a directory"
	exit 1
fi

if [[ "/" = "$target_directory" ]]
then 
	echo "Cannot run `takeout` on root directory"
	exit 2
fi

# `man zshexpn`. Glob Qualifiers
for FILE in $target_directory/*(D)
do 
	mv "$FILE" "$parent_directory" || exit $?
done 

rmdir "$target_directory"
