# This github action will check if the backup was successfully restored on
# macos and Ubuntu
name: Test restore script
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install backup
        run: zsh ./restore.sh
        shell: zsh {0}
      - name: Check backup
        run: |
          test -d $HOME/Demeter
          test -f $HOME/.zshrc
          test -f $HOME/.zshenv
          cat $HOME/.gitconfig | grep "67512202+Altair-Bueno@users.noreply.github.com"
