# This github action will check if the backup was successfully restored on
# macos and Ubuntu
name: Test backup script
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
    runs-on : ${{ matrix.os }}
    steps:
      - name: Install backup
        run: curl https://raw.githubusercontent.com/Altair-Bueno/Demeter/master/restore.sh | bash
      - name: Check backup
        run: |
          test -d $HOME/Demeter
          test -f $HOME/.vimrc
          test -f $HOME/.p10k.zsh
          cat $HOME/.gitconfig | grep "67512202+Altair-Bueno@users.noreply.github.com"
      - name: Update and reinstall
        run: curl https://github.com/Altair-Bueno/Demeter/raw/master/restore.sh | bash