# This github action will check if the backup was successfully restored on
# macos and Ubuntu
name: Test backup script
on:
  workflow_dispatch:
env:
  RESTORE: "https://raw.githubusercontent.com/Altair-Bueno/Demeter/master/restore.sh"
jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install backup
        run: eval `curl "$RESTORE"`
        shell: zsh {0}
      - name: Check backup
        run: |
          test -d $HOME/Demeter
          test -f $HOME/.zshrc
          test -f $HOME/.zshenv
          cat $HOME/.gitconfig | grep "67512202+Altair-Bueno@users.noreply.github.com"
